### ISSUE TITLE
Propuestas LAb

### ISSUE THREAD

**Issue by gitainhoa** [BlockchainEspanaHQ/CommunityLab#15]

**Comment by angelesbl** [comment]
**Alex** propone montar  organizaciones caritativas descentralizadas: selección de proyecto y entrega previa validación.

**Comment by alexpreukschat** [comment]
**Enrique y Edu** proponen el desarrollo de un Bitcoin development environment with Docker &

**Comment by alexpreukschat** [comment]
**David** nos ha pasado tutoriales para dos redes de Tesnet de Ethereum: Rinkeby (Clique Consensus) y ROPSTEN (Proof of Work)

**Comment by alexpreukschat** [comment]
**Jose Antonio** n

**Comment by alexpreukschat** [comment]
**Xus**, que nos ha montado la *proof of work* del LAB, nos manda un artículo  para analizar cripto markets con python y los jupyter notebooks (para los interesados en data science): https://blog.patricktriest.com/analyzing-cryptocurrencies-python/

**Comment by alexpreukschat** [comment]
**Gustavo** está desarrollando un un proyecto de movilidad en ciudades y bien común sobre blockchain, en el que trabajan él como UX/Product Design y un desarrollador de  machine learning. 
**¡Gracias Gus!**

**Comment by alexpreukschat** [comment]
**Ainhoa** propone el desarrollo del smart contract del LAB, y la construcción de la blockchain de BlockchainEspaña para temas de certificaciones etc…

**Comment by gitainhoa** [comment]
En el mismo sentido que **Jose Antonio**, **Javi** (o **I love C** but very much) se ofrece a enseñarnos a crear una blockchain con python. 
**¡Javi, crack, muchas gracias!**
